
[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"    # use "cargo fix" to fix for compatibility with different Rust edition.
license = "MIT OR Apache-2.0"
description = "Accumulate knowledge of my study on Rust language"
authors = ["MeiHui FAN <mhfan@ustc.edu>"]
exclude = ["tests"]

[workspace]
#members = [""]
#exclude = ["hello-wasm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.*"
num-bigint = "0.4.*"
#itertools = "0.10.*"
yansi = "0.5.*"

[lib]
#proc-macro = true

[profile.release]
panic = 'abort'

[profile.release-lto]
inherits = "release"
lto = true
