
[package]
name = "hello-rust"
version = "0.2.1"
edition = "2021"    # use 'cargo fix' to fix for compatibility with different Rust edition.
license = "MIT OR Apache-2.0"
description = "Accumulate knowledge of my study on Rust language"
authors = ["MeiHui FAN <mhfan@ustc.edu>"]
#exclude = ["tests", "benches"]

[workspace]
#members = [""]
#exclude = ["hello-wasm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# 'cargo tree', to visualize the dependency graph
[dependencies]
rand = "0.8.*"
num-bigint = "0.4.*"
#itertools = "0.10.*"
#rustc-hash = "1.1.*"
yansi = "0.5.*"
#num = "0.4.*"

[dev-dependencies]
#pprof = { version = "0.9.*", features = ["flamegraph"] }
criterion = "0.3.*"
#bencher = "0.1.*"

[[bench]]
name = "comp24_bench"
#cargo_bench_support = true
#html_reports = false
harness = false

[lib]
#crate-type = ["cdylib", "lib"]
#proc-macro = true

[profile.release]
incremental = true
panic = 'abort'
#opt-level = 3
#strip = true    # Automatically strip symbols from the binary.
debug = true    # for flamegraph
#lto = true

#[profile.release-lto]
#inherits = "release"
